import { Inter } from "next/font/google";
import "./globals.css";


// Redux
import { Providers } from "./GlobalRedux/provier";

import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Neptune",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="bg-white">
			<body className={inter.className}>
				<Providers>
					<Header/>
					{children}
				</Providers>
			</body>
		</html>
	);
}
